#Map配置
server:
  port: 8081
#mysql数据库连接信息

#配置mybatis的信息
#spring集成Mybatis环境
mybatis:
  #pojo别名扫描包
  type-aliases-package: com.wdx.domain
  mapper-locations: classpath:mapper/*Mapper.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/recruit?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root